### ISSUE TITLE
no macos/osx support - incorrectly setup in packagecontrol

### ISSUE THREAD

**Issue by keen99** [Haiquan-27/SSH-Panel#6]
in packagecontrol, this package is not restricted to linux/windows only:

https://packagecontrol.io/packages/SSH-Panel

![image](https://github.com/user-attachments/assets/0236c3e0-3387-45e0-bd24-30e161ee12a3)

so macos users dont know they can't use it until they install it and runs the deps installer:

![image](https://github.com/user-attachments/assets/c96a9916-015b-4895-89a4-4d84fd848ece)

please setup the apropos metadata in packagecontrol...

**Comment by Haiquan-27** [comment]
`"Platforms": ["Windows", "Linux"]` were removed on September 4, 2024 for platform wide adaptation see [detail](https://github.com/wbond/package_control_channel/pull/8965)
At now,the metadata for this package in [channel_v3](https://packagecontrol.io/channel_v3.json) is
``` json
{
	"name": "SSH-Panel",
	"description": "sublime text SSH Remote editor",
	"authors": [
		"Haiquan"
	],
	"homepage": "https://github.com/Haiquan-27/SSH-Panel",
	"previous_names": [],
	"labels": [
		"file navigation",
		"file creation",
		"remote"
	],
	"readme": "https://raw.githubusercontent.com/Haiquan-27/SSH-Panel/main/README.md",
	"issues": "https://github.com/Haiquan-27/SSH-Panel/issues",
	"donate": null,
	"buy": null,
	"releases": [
		{
			"platforms": [
				"*"
			],
			"sublime_text": ">=3211",
			"version": "1.3.2",
			"url": "https://codeload.github.com/Haiquan-27/SSH-Panel/zip/v1.3.2",
			"date": "2024-09-07 16:01:53"
		},
		{
			"platforms": [
				"*"
			],
			"sublime_text": ">=3211",
			"version": "1.2.2",
			"url": "https://codeload.github.com/Haiquan-27/SSH-Panel/zip/v1.2.2",
			"date": "2024-04-27 17:07:46"
		},
		{
			"platforms": [
				"*"
			],
			"sublime_text": ">=3211",
			"version": "1.0.0",
			"url": "https://codeload.github.com/Haiquan-27/SSH-Panel/zip/v1.0.0",
			"date": "2022-02-26 09:36:28"
		}
	]
}
```
metadata settings of the package should be fine
your may need to check your configuration (Package Control.sublime-settings@"channels")，or check if there is network cache exists? or is it because you have already installed this package that it does not appear in the installable list?
![image](https://github.com/user-attachments/assets/26304ba8-8663-4d98-8c37-3fb80e204a23)

**Comment by Haiquan-27** [comment]
macos(osx) is support,This is just a 404 error
The reason for this error is that the dependency package corresponding to the platform cannot be found
For macOS, `py38_osx_x64.zip` or `py38_osx_arm64.zip` should be downloaded
![image](https://github.com/user-attachments/assets/d52b7d18-16f6-49b5-a416-fb16a47ca6f5)

**Comment by Haiquan-27** [comment]
This package will be downloaded by searching for suitable dependency packages based on your current OS platform and ST version,the download URL is determined by the following code:
``` Python
...
	self.dependencies_url = dependencies_url.format(
		source = dependencies_source[source],
		py_version = "py%d%d"%sys.version_info[:2], # py33 | py38
		platform = sublime.platform(), # 'osx' | 'linux' | 'windows'
		arch = sublime.arch() # 'x32' | 'x64' | 'arm64'
	)
...
	SshPanelOutputCommand(self.window.active_view()).run(sublime.Edit,content="",display=False,clean=True)
		if "404" in str(e):
			LOG.E("UNSUPPORTED PLATFORM")
...
```
[provided file](https://github.com/Haiquan-27/SSH-Panel-doc-annex/releases/tag/public) are as follows:
|file name|sha256sum|description|
|--------------|-----------------|----------------|
| py33_windows_x64.zip |f0696dc8319414262682cfda1a24b943991d39fc3818bf9cfb5b8922aa7a1f70  | ssh-panel v1.3.1 + |
| py38_linux_x64.zip |bd601ff78e4ce9be1f445c8038e2e0373c1092c6147ae6fa309983e2cc824856  | ssh-panel v1.3.1 + |
|py38_windows_x64.zip |1eb60e22b36eb499b5e4356dece4c0f9095990dafce8bfc6fbae9b489ba96464  | ssh-panel v1.3.1 + |
| py33_windows_x32.zip |871a165747c8f91f901b11bc9295f23ddc0209aea24f85e8aa1290df7a839f26| ssh-panel v1.3.1 + |
| py38_osx_x64.zip | 25d60dbad2651e57468722d5c9999136a5727d3c1e097bb9417e029a7f14bfec | ssh-panel v1.3.1 + |
|py38_osx_arm64.zip | ee8aab9e0d219d07fd9bb8be450c1154977d8ddc4ac68d32a0fcc8c4723172e5 | ssh-panel v1.3.1 + |
| linux.zip |73c00727e11e7ffe8dd9ef1304ec76827d71a6ddaa4a2e131dfc903c62f395a5  | ssh-panel v1.3.0 |
| windows.zip |1893f475e1d241be2aaf6ecacd8802cdc8bb071c88c9a44968aeff58b2f33422  | ssh-panel v1.3.0 |

For osx_arm64, `ssh_panel_install_dependencies` command has not been tested (Because I Have Not)
The name of the dependent file is inferred from the possible values provided in the [API documentation](https://www.sublimetext.com/docs/api_reference.html#sublime.arch)

You can try one of the following to solve this problem:
- Reinstall Package,Ensure that the package version is the latest (v1.3.2)
- Manual download the [required dependency files](https://github.com/Haiquan-27/SSH-Panel-doc-annex/releases/tag/public) and unzip them to the corresponding location by yourself
- Build the necessary dependencies on your own
```
├─── py38_osx_arm64 (sublime tet 4+)
|	 └── dist-packages
|		 ├── bcrypt (4.2.0)
|		 ├── cryptography (43.0.0)
|		 ├── cffi (1.17.0)
|		 ├── nacl (1.5.0)
|		 ├── paramiko (3.4.1)
|		 └── pycparser (2.22)
```

**Comment by Haiquan-27** [comment]
If your issue persists, please obtain and provide the following information in the ST console:
- arch name
- platform name
- sublime python version

Execute the following code in the console
``` Python
import sys
sys.version_info
sublime.platform()
sublime.arch() # if your use macos_m1/m2, "arm64" should be returned
```
![image](https://github.com/user-attachments/assets/9e4735de-05e6-48d6-8671-26e3e7de685a)
